[package]
name = "zlorbrs-service"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "1.0.228"
serde_json = "1.0.145"
zlorbrs-lib = { path = "../zlorbrs-lib"}
env_logger = "0.11.8"
log = "0.4.28"
git2 = "0.20.2"
