[package]
name = "zlorbrs-ctl"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {version="4.5.48", features=["derive"]}
log = "0.4.28"
zlorbrs-lib = { path = "../zlorbrs-lib"}
env_logger = "0.11.8"
